name: Build and deploy evolt-be to Azure Web App

on:
  push:
    branches: [main]
    paths:
      - "apps/evolt-be/**"
      - ".github/workflows/**"
      - "package.json"
      - "yarn.lock"
      - "pnpm-lock.yaml"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      WORKDIR: apps/evolt-be

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: npm install, build (backend only)
        working-directory: ${{ env.WORKDIR }}
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job (backend only)
        uses: actions/upload-artifact@v4
        with:
          name: evolt-be
          path: ${{ env.WORKDIR }}
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: evolt-be
          path: ./deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2052BDE0285F46FE9098264BE78B498D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BD5589DF03BB4DDE81F7EE8EF0A9CC2A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B7886D8665745218F696E8EDF748949 }}

      - name: Deploy to Azure Web App (backend subfolder)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "useevolt"
          slot-name: "Production"
          package: "./deploy/"
