name: Build and deploy evolt-be to Azure Web App

on:
    push:
        branches: [main]
        paths:
            - "apps/evolt-be/**"
            - ".github/workflows/**"
            - "package.json"
            - "yarn.lock"
            - "pnpm-lock.yaml"
            - "package-lock.json"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        env:
            WORKDIR: apps/evolt-be

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            # If your backend is standalone:
            - name: npm install, build (backend only)
              working-directory: ${{ env.WORKDIR }}
              run: |
                  npm install
                  npm run build --if-present

            - name: Upload artifact for deployment job (backend only)
              uses: actions/upload-artifact@v4
              with:
                  name: evolt-be
                  path: ${{ env.WORKDIR }}
                  if-no-files-found: error

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: evolt-be
                  path: ./deploy

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9EAD8498E6D74557990CFE6532B8E91A }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F5744CE293F47C3973A443FED12B7E3 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_997F3705C2D74321950763E2947B57BA }}

            - name: Deploy to Azure Web App (backend subfolder)
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "evolt"
                  slot-name: "Production"
                  package: "./deploy/evolt-be" #
