name: Build and deploy evolt-be to Azure Web App

on:
  push:
    branches: [main]
    paths:
      - "apps/evolt-be/**"
      - ".github/workflows/**"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      WORKDIR: apps/evolt-be

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies (with devDependencies)
        working-directory: ${{ env.WORKDIR }}
        run: yarn install --frozen-lockfile

      - name: Build project
        working-directory: ${{ env.WORKDIR }}
        run: yarn build

      - name: Prepare production artifact
        working-directory: ${{ env.WORKDIR }}
        run: |
          rm -rf src test .husky .eslint* .prettier* tsconfig.json jest.config.js
          echo "✅ Ready to deploy with node_modules intact"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: evolt-be
          path: ${{ env.WORKDIR }}
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: evolt-be
          path: ./deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2052BDE0285F46FE9098264BE78B498D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BD5589DF03BB4DDE81F7EE8EF0A9CC2A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B7886D8665745218F696E8EDF748949 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "useevolt"
          slot-name: "Production"
          package: "./deploy/"
